logging:
  file:
    name: ${logging.file.path}/${spring.application.name}.log
    path: logs
  logback:
    rollingpolicy:
      file-name-pattern: ${logging.file.path}/${spring.application.name}-%d{yyyy-MM-dd}-%i.log
      max-file-size: 10MB
spring:
  main:
    banner-mode: log
  application:
    name: Demo
    version: SNAPSHOT-0.0.1
